### ISSUE TITLE
add base16-default (and other variants) themes

### ISSUE THREAD

**Issue by oryband** [acrisci/i3-style#11]
http://chriskempson.github.io/base16/

**Comment by oryband** [comment]
I've found [this post][post] with the following configuration, but I'm not 100% sure the colors are straight. For example the color values are different from the `.Xresources` base16 colors:
```
background #151515
statusline #505050
separator #303030
focused_workspace  #c7a3c0 #aa759f #ffffff
active_workspace   #aa759f #303030 #ffffff
inactive_workspace #505050 #303030 #707070
urgent_workspace   #c86f70 #ac4142 #ffffff
```

[post]: https://bbs.archlinux.org/viewtopic.php?pid=1281498#p1281498

**Comment by oryband** [comment]
Also, if it is to any help to someone, this is the window (not i3 bar) base16-default colors, taken from the post above:
```
client.focused          #B2C48D #90A959 #ffffff #90A959
client.focused_inactive #90a959 #303030 #b0b0b0 #303030
client.unfocused        #505050 #303030 #b0b0b0 #303030
client.urgent           #C86F70 #AC4142 #ffffff
client.background #151515
```

**Comment by acrisci** [comment]
It would be cool if i3-style could parse a config and automatically give you a theme from the config.

**Comment by acrisci** [comment]
I ran it through i3-style with the new `--to-theme` option and it gave me this output. Let me know if that looks right. I think the guy's screenshot 404'd so I can't check.

```yaml
# vim: filetype=yaml
---
meta:
  description: AUTOMATICALLY GENERATED THEME
colors:
  darkseagreen: "#B2C48D"
  darkkhaki: "#90A959"
  white: "#ffffff"
  darkkhaki1: "#90a959"
  darkslategrey: "#303030"
  darkgrey: "#b0b0b0"
  dimgray: "#505050"
  indianred: "#C86F70"
  indianred1: "#AC4142"
  black: "#151515"
  thistle: "#c7a3c0"
  plum: "#aa759f"
  dimgrey: "#707070"
  indianred2: "#c86f70"
  indianred3: "#ac4142"
window_colors:
  focused:
    border: darkseagreen
    background: darkkhaki
    text: white
    indicator: darkkhaki
  focused_inactive:
    border: darkkhaki1
    background: darkslategrey
    text: darkgrey
    indicator: darkslategrey
  unfocused:
    border: dimgray
    background: darkslategrey
    text: darkgrey
    indicator: darkslategrey
  urgent:
    border: indianred
    background: indianred1
    text: white
bar_colors:
  background: black
  statusline: dimgray
  separator: darkslategrey
  focused_workspace:
    border: thistle
    background: plum
    text: white
  active_workspace:
    border: plum
    background: darkslategrey
    text: white
  inactive_workspace:
    border: dimgray
    background: darkslategrey
    text: dimgrey
  urgent_workspace:
    border: indianred2
    background: indianred3
    text: white
```
